## Bingo Site Configuration
## This file contains non-sensitive configuration options
## Sensitive credentials should be in .env file

## Site Configuration
site:
  title: ToadBox Bingo
  description: A customizable bingo board site
  url: http://localhost:3000  # Change for production
  defaultTheme: light
  availableThemes:
    - light
    - dark
    - high-contrast
  serverUsername: server
  contact:
    email: ""
    supportUrl: ""

## Server Configuration  
server:
  port: 3000
  host: localhost
  cors:
    enabled: true
    origins:
      - http://localhost:3001  # React dev server
      - http://localhost:3000  # Production server

## Authentication Configuration
auth:
  allowAnonymous: true
  sessionTimeout: 24h
  requireApproval:
    local: true      # Local accounts need admin approval
    authentik: false # Authentik accounts auto-approved
  providers:
    authentik:
      enabled: false  # Set to true and configure credentials in .env
      # Credentials: AUTHENTIK_CLIENT_ID, AUTHENTIK_CLIENT_SECRET

## Board Configuration
boards:
  limits:
    maxBoardsPerUser: 10
    maxCellsPerBoard: 25
    maxBoardVersions: 50
  defaultSettings:
    size: 5
    freeSpace: true
    freeSpacePosition:
      row: 2
      col: 2
    chatEnabled: true
    publicChat: true
    mentionNotifications: true
    editNotifications: true
    requireApproval: false

## File Storage Configuration
storage:
  images:
    maxSizeMB: 5
    allowedTypes:
      - image/jpeg
      - image/png
      - image/gif
      - image/webp
    path: ./uploads/images
    compressionEnabled: true
    compressionQuality: 80

## Feature Toggles
features:
  offlineMode: false      # Disable external services (Discord, etc.)
  analytics: false        # Enable usage analytics
  rateLimiting: true      # Enable rate limiting
  websockets: true        # Enable real-time features
  fileUploads: true       # Enable image uploads  
  adminPanel: true        # Enable admin interface

## Notification Configuration
notifications:
  enabled: true
  defaultPreferences:
    mentions: true
    edits: true
    approvals: true
    system: true

## Logging Configuration
logging:
  level: info            # debug, info, warn, error
  logToFiles: true
  logPath: ./logs
  errorReporting: true   # Store errors in database for admin panel
  performance: true      # Track performance metrics

## Security Configuration
security:
  rateLimiting:
    windowMs: 900000     # 15 minutes in milliseconds
    maxRequests: 500     # Max requests per window per IP
  helmet:
    enabled: true
    contentSecurityPolicy: true
  cookieSettings:
    httpOnly: true
    sameSite: strict
    # secure: true (automatically set in production)

## Memory Cache Configuration
cache:
  enabled: true
  maxSizeMB: 2048              # Maximum cache size in MB (400MB default, can set to 5GB = 5120)
  defaultTTL: 3600            # Default TTL in seconds (1 hour)
  cleanupInterval: 300        # Cleanup interval in seconds (5 minutes)
  strategies:
    database: 
      enabled: true
      ttl: 1800               # 30 minutes for DB queries
    sessions:
      enabled: true  
      ttl: 7200               # 2 hours for session data
    boards:
      enabled: true
      ttl: 900                # 15 minutes for board data
    static:
      enabled: true
      ttl: 3600               # 1 hour for static content

## Database Configuration  
database:
  path: ./src/data/bingo.sqlite
  backupEnabled: true
  backupInterval: 24h

## Admin Account Configuration
## Credentials are set in .env file:
## ROOT_ADMIN_USERNAME, ROOT_ADMIN_PASSWORD, ROOT_ADMIN_EMAIL
